# Generated by Django 5.1.6 on 2025-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("donation_time", models.DateTimeField(verbose_name="捐赠时间")),
                ("donor_name", models.CharField(max_length=100, verbose_name="捐赠人")),
                ("donation_worth", models.FloatField(verbose_name="捐赠金额")),
                (
                    "donation_object",
                    models.CharField(max_length=100, verbose_name="捐赠物品"),
                ),
                (
                    "donation_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="捐赠编号"
                    ),
                ),
            ],
        ),
    ]
