# Generated by Django 5.1.6 on 2025-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="donation_worth",
            field=models.FloatField(default=0, verbose_name="捐赠金额"),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_name",
            field=models.CharField(
                default="佚名", max_length=100, verbose_name="捐赠人"
            ),
        ),
    ]
