# Generated by Django 5.1.6 on 2025-03-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "board_id",
                    models.IntegerField(
                        help_text="板块唯一标识符，自动递增",
                        primary_key=True,
                        serialize=False,
                        verbose_name="板块编号",
                    ),
                ),
                (
                    "board_title",
                    models.CharField(
                        default="新板块", max_length=100, verbose_name="板块文字"
                    ),
                ),
            ],
            options={
                "verbose_name": "文章板块",
                "verbose_name_plural": "文章板块",
                "ordering": ["board_id"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_title",
                    models.CharField(
                        default="新文章", max_length=100, verbose_name="文章名字"
                    ),
                ),
                (
                    "entry_writer",
                    models.CharField(
                        default="佚名", max_length=100, verbose_name="文章作者"
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布日期"),
                ),
                (
                    "entry_content",
                    models.TextField(default="", verbose_name="文章内容"),
                ),
                (
                    "entry_label",
                    models.SlugField(
                        help_text="用于URL的英文标识（示例：python-tutorial）",
                        max_length=100,
                        unique=True,
                        verbose_name="文章标签",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        help_text="选择文章归属的板块",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="document.board",
                        verbose_name="所属板块",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章条目",
                "verbose_name_plural": "文章条目",
                "ordering": ["-entry_time"],
            },
        ),
    ]
