# Generated by Django 5.1.6 on 2025-03-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "level_id",
                    models.PositiveIntegerField(
                        help_text="用于URL的价位段标识（示例：1代表3000元以下）",
                        primary_key=True,
                        serialize=False,
                        verbose_name="价位编号",
                    ),
                ),
                (
                    "level_range",
                    models.CharField(
                        help_text="示例：3000-5000元",
                        max_length=50,
                        verbose_name="价格区间",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格等级",
                "verbose_name_plural": "价格等级",
                "ordering": ["level_id"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_label",
                    models.SlugField(
                        help_text="仅包含英文数字的URL友好标识（示例：lenovo-yoga）",
                        max_length=100,
                        unique=True,
                        verbose_name="产品标签",
                    ),
                ),
                (
                    "book_name",
                    models.CharField(max_length=100, verbose_name="产品名称"),
                ),
                (
                    "book_preview",
                    models.ImageField(
                        blank=True,
                        help_text="图片将存储在 static/suggestion/images/previews/",
                        null=True,
                        upload_to="previews/",
                        verbose_name="产品预览图",
                    ),
                ),
                ("book_cpu", models.CharField(max_length=100, verbose_name="处理器")),
                ("book_gpu", models.CharField(max_length=100, verbose_name="显卡")),
                ("book_detail", models.TextField(verbose_name="详细配置")),
                ("book_crowd", models.TextField(verbose_name="适用人群")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="suggestion.level",
                        verbose_name="所属价位",
                    ),
                ),
            ],
            options={
                "verbose_name": "笔记本推荐",
                "verbose_name_plural": "笔记本推荐",
                "indexes": [models.Index(fields=["book_label"], name="book_label_idx")],
            },
        ),
    ]
