# Generated by Django 5.1.6 on 2025-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_preview",
            field=models.ImageField(
                blank=True,
                help_text="图片将存储在 static/media/previews/",
                null=True,
                upload_to="previews/",
                verbose_name="产品预览图",
            ),
        ),
    ]
