# Generated by Django 5.1.6 on 2025-03-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sign",
            name="nick_name",
            field=models.CharField(
                default="匿名用户",
                help_text="将在评价中显示的名称",
                max_length=50,
                verbose_name="用户昵称",
            ),
        ),
    ]
