# Generated by Django 5.1.6 on 2025-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management_name",
                    models.CharField(help_text="历代社长名字", max_length=100),
                ),
                (
                    "photo_path",
                    models.CharField(
                        help_text="存放对应介绍图片的地址", max_length=255
                    ),
                ),
                ("introduction", models.TextField(help_text="介绍文本")),
                (
                    "management_time",
                    models.CharField(help_text="“在位”时间", max_length=100),
                ),
                ("op_id", models.IntegerField(help_text="唯一性检索标定", unique=True)),
            ],
        ),
    ]
