# Generated by Django 5.1.6 on 2025-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("introduction", "0002_operator_management_campus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="photo_path",
        ),
        migrations.AddField(
            model_name="operator",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="请上传社长照片（推荐尺寸：400x400像素）",
                upload_to="introduction/images/",
                verbose_name="社长照片",
            ),
        ),
    ]
