# Generated by Django 5.1.6 on 2025-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("introduction", "0003_remove_operator_photo_path_operator_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="introduction",
            field=models.TextField(default="无", verbose_name="人物简介"),
        ),
        migrations.AlterField(
            model_name="operator",
            name="management_campus",
            field=models.CharField(
                default="未知", max_length=120, verbose_name="所属学院"
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="management_name",
            field=models.CharField(
                default="佚名", max_length=100, verbose_name="社长姓名"
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="management_time",
            field=models.CharField(
                default="未知", max_length=100, verbose_name="任期时间"
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="op_id",
            field=models.IntegerField(
                help_text="唯一标识符", unique=True, verbose_name="社长编号"
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="operators/", verbose_name="社长照片"
            ),
        ),
    ]
